version: "3.9"

services:
  app:
    build: .
    container_name: ozon_drugs_app
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # подключаем сертификаты из хоста в контейнер
      - ./certs:/etc/letsencrypt:ro
    environment:
      - NODE_ENV=production
      - PORT=3000
